version: "3"

tasks:
  default:
    cmds:
      - task: build

    deps:
      - install

  build:
    cmd: pnpm run build
    deps:
      - install

  install:
    cmd: pnpm install
    run: once
    status:
      - test -d node_modules

  example:
    desc: "Run parse-export-chat-json example"
    dir: examples/parse-export-chat-json
    cmds:
      - pnpm install
      - node index.js
    deps:
      - build

  mise:
    desc: "Mise installation"
    cmd: mise install
