name: Code Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm exec tsc --noEmit

      - name: Check build
        run: pnpm build

      - name: Verify package files
        run: |
          echo "Checking dist files..."
          ls -la dist/
          echo "Verifying CommonJS export..."
          node -e "const { CopilotChatAnalyzer } = require('./dist/index.cjs'); console.log('✅ CommonJS import successful:', typeof CopilotChatAnalyzer);"
          echo "Verifying ES Module export..."
          node -e "import('./dist/index.mjs').then(m => console.log('✅ ESM import successful:', typeof m.CopilotChatAnalyzer))"
